frontend-razor/frontend-razor/Controllers/MembershipController.cs
using frontend.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Security.Claims;

namespace frontend.Controllers
{
    public class MembershipController : Controller
    {

        private readonly IHttpClientFactory _httpClientFactory;

        public MembershipController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public IActionResult Confirmation() 
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var membresias = await GetMembresias();

                if (membresias != null)
                {

                    ViewBag.Membresias = membresias;
                }
                else
                {

                    ViewBag.ErrorMessage = "Error fetching membresias data.";
                }
            }
            catch (Exception ex)
            {

                ViewBag.ErrorMessage = $"An error occurred: {ex.Message}";
            }

            return View();
        }


        private async Task<List<Membresia>> GetMembresias()
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                var url = $"https://localhost:7061/api/Membresias";

                using (var response = await client.GetAsync(url))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        return await response.Content.ReadFromJsonAsync<List<Membresia>>();
                    }
                    else
                    {

                        return null;
                    }
                }
            }
            catch (HttpRequestException)
            {
                return null;
            }
        }

        public ActionResult AcceptarMembresia(int MembresiaID)
        {

            var idUsuario = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.idUsuario = idUsuario;
            ViewBag.MembresiaID = MembresiaID;
            return View(MembresiaID);
        }

    }
}

frontend-razor/frontend-razor/Views/Membership/AcceptarMembresia.cshtml
@model int

<head>
    <style>
        h1 {
            margin-top: 100px;
        }
    </style>
</head>

<!DOCTYPE html>
<html lang="en">
<body>
    <div class="container mt-5">
        <h1>Confirmar membresía</h1>
        <div class="card">
            <div class="card-body">
                <h5>Confirmar Selección</h5>
                <p id="nombre" name="nombre">Has seleccionado: </p>
                <p id="precio" name="precio">Precio: </p>
                <button type="button" onclick="guardarCambios()">Guardar Cambios</button>
            </div>
        </div>
    </div>
</body>

<script>
    document.addEventListener("DOMContentLoaded", function () {

        var MembresiaID = @Model;

        fetch(`https://localhost:7061/api/Membresias/${MembresiaID}`)
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json();
            })
            .then(data => {
                document.getElementById("nombre").textContent = "Has seleccionado: " + data.nombre;
                document.getElementById("precio").textContent = "Precio: " + data.precio;

            })
            .catch(error => {
                console.error('Error fetching data:', error);
            });
    });

    function guardarCambios() {
        var MembresiaID = @Model;
        var idUsuario = @ViewBag.idUsuario

        var formData = {
            idUsuario: idUsuario,
            membresiaID: MembresiaID
        };

        fetch(`https://localhost:7061/api/Usuario/${idUsuario}`, {
            method: 'PUT',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData),
        })
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.text();
            })
            .then(data => {
                console.log('Data updated successfully:', data);
                window.location.href = '/Member';
            })
            .catch(error => {
                console.error('Error updating data:', error);
            });

    }
</script>


</html>

frontend-razor/frontend-razor/Views/Membership/Index.cshtml
@model IEnumerable<frontend.Models.Membresia>

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Cuerpo&Mente - Elegir planes disponibles</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        .card-row {
            display: flex;
            justify-content: space-around;
            align-items: center;
            flex-wrap: wrap;
            margin-bottom: 20px;
        }

        .card {
            background-color: #fff;
            border: 1px solid #ccc;
            transition: transform 0.2s;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 200px;
            text-align: center;
            margin: 10px;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }

        header {
            background-color: #fff;
            color: black;
            padding: 10px;
            text-align: center;
        }

        .membresia-section {
            display: flex;
            justify-content: space-around;
            align-items: center;
            flex-wrap: wrap;
            margin-top: 20px;
        }

        .membresia-card {
            text-align: center;
            background-color: #fff;
            border: 1px solid #ccc;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            overflow: hidden;
            margin: 10px;
            padding: 20px;
            width: 300px;
            transition: transform 0.2s;
        }

            .membresia-card:hover {
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
                transform: scale(1.05);
            }

            .membresia-card .titulo {
                background-color: #00b894;
                color: #fff;
                padding: 10px;
                text-align: center;
                font-size: 1.2em;
            }

            .membresia-card .precio {
                text-align: center;
                font-size: 1.5em;
                margin: 10px 0;
            }

            .membresia-card .boton {
                display: block;
                width: 100%;
                padding: 10px;
                background-color: #00b894;
                color: #fff;
                text-align: center;
                text-decoration: none;
                border: none;
                cursor: pointer;
            }

                .membresia-card .boton:hover {
                    background-color: #00a897;
                }

            
    </style>
</head>

<body>
    @if (ViewBag.Membresias != null)
    {
        <div class="container">
            <section class="membresia-section">
                @foreach (var tipoMembresia in ViewBag.Membresias)
                {
                    <div class="membresia-card">
                        <div class="titulo">@tipoMembresia.Nombre</div>
                        <div class="contenido">@tipoMembresia.Descripcion</div>
                        <div class="precio">₡@tipoMembresia.Precio</div>
                        @Html.ActionLink("Seleccionar", "AcceptarMembresia", "Membership", new { area = "", MembresiaID = @tipoMembresia.MembresiaID }, new { @class = "" })
                    </div>
                }
            </section>
    </div>
    }
</body>
</html>